name: nodejs eks feature
on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
      component: 
        required: true
        type: string
env:
  project: "${{ inputs.project}}"
  component: "${{ inputs.component }}"
jobs:
  build-nodejs: 
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: action/checkout@v7
      
    - name: list files
      run: |
        ls -l